export const siteConfig = {
  businessName: "Garabedian Plumbing, Heating & Cooling",
  tagline: "When it breaks, you call Garabedian.",
  trade: "Plumbing, Heating & Cooling",
  phone: "508-757-4803",
  phoneHref: "tel:5087574803",
  emergencyPhone: "508-757-4803",
  emergencyPhoneHref: "tel:5087574803",
  email: "info@garabedianphc.com",
  address: {
    street: "208 Austin Street",
    city: "Worcester",
    state: "MA",
    zip: "01609",
    full: "208 Austin Street, Worcester, MA 01609",
  },
  serviceArea: "Worcester & Central Massachusetts",
  serviceAreaExtended:
    "Worcester, Shrewsbury, Auburn, Holden, Grafton, Northborough, Millbury, Leicester, West Boylston, Boylston, Westborough",
  serviceAreaList: [
    "Worcester",
    "Shrewsbury",
    "Auburn",
    "Holden",
    "Grafton",
    "Northborough",
    "Millbury",
    "Leicester",
    "West Boylston",
  ],
  license: "MA Master Plumber Lic. #11427",
  epa: "EPA 608 Certified",
  insurance: "Fully licensed, bonded, and insured up to $2M",
  bbb: "",
  hours: {
    weekday: "Monday - Friday: 8 AM - 4:30 PM",
    saturday: "Saturday: Closed",
    sunday: "Sunday: Closed",
    emergency: "24/7 Emergency Dispatch",
  },
  stats: {
    years: "40+",
    projects: "206",
    satisfaction: "100%",
    rating: "4.2",
  },
  founded: "1916",
  founderStory: "Founded by Hagop Garabedian",
  primaryDomain: process.env.NEXT_PUBLIC_PRIMARY_DOMAIN || "",
  googleReviewLink: "https://www.google.com/search?sca_esv=453cbd3ddf1993fe&hl=en-US&gl=us&sxsrf=ANbL-n5Zmv-iRzNZLSo_x191xSwUe7MgYw:1780695595428&si=AL3DRZHrmvnFAVQPOO2Bzhf8AX9KZZ6raUI_dT7DG_z0kV2_x4Wkn88ql-pgjfbd7kMUr4qLnpXx3EM-U5ILeHHEo8PehCzlfgCGzfgJH02fOoqhV9HU9ZPL8Y1yBpFFdZHTh6lyG3s0mQC4gwPHQ81vz4t1RdZ1cGw0vGouTWp9R9TBpW1_VFc%3D&q=Garabedian+Plumbing+%26+Heating+Inc.+Reviews&sa=X&ved=2ahUKEwiupqyDiPGUAxUVm4kEHVrdLzsQ0bkNegQIJRAH&cshid=1780695618274074&biw=1912&bih=956&dpr=1",
  googleWriteReviewLink: "https://search.google.com/local/writereview?placeid=ChIJb-pZpo8G5IkR6-gkX-i8GUg",
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "About", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
  footerServices: [
    { label: "Emergency Service", href: "/contact" },
    { label: "Plumbing Repair", href: "/services" },
    { label: "Heating Systems", href: "/services" },
    { label: "Air Conditioning", href: "/services" },
  ],
  footerCompany: [
    { label: "About Us", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
} as const;
