export const siteConfig = {
  businessName: "Garabedian Plumbing, Heating & Cooling",
  tagline: "When it breaks, you call Garabedian.",
  trade: "Plumbing, Heating & Cooling",
  phone: "508-757-4803",
  phoneHref: "tel:5087574803",
  emergencyPhone: "508-757-4803",
  emergencyPhoneHref: "tel:5087574803",
  email: "info@garabedianphc.com",
  address: {
    street: "208 Austin Street",
    city: "Worcester",
    state: "MA",
    zip: "01609",
    full: "208 Austin Street, Worcester, MA 01609",
  },
  serviceArea: "Worcester & Central Massachusetts",
  serviceAreaExtended:
    "Worcester, Shrewsbury, Auburn, Holden, Grafton, Northborough, Millbury, Leicester, West Boylston, Boylston, Westborough",
  serviceAreaList: [
    "Worcester",
    "Shrewsbury",
    "Auburn",
    "Holden",
    "Grafton",
    "Northborough",
    "Millbury",
    "Leicester",
    "West Boylston",
  ],
  license: "MA Master Plumber Lic. #11427",
  epa: "EPA 608 Certified",
  insurance: "Fully licensed, bonded, and insured up to $2M",
  bbb: "",
  hours: {
    weekday: "Monday - Friday: 8 AM - 4:30 PM",
    saturday: "Saturday: Closed",
    sunday: "Sunday: Closed",
    emergency: "24/7 Emergency Dispatch",
  },
  stats: {
    years: "40+",
    projects: "1,428",
    satisfaction: "100%",
    rating: "4.2",
  },
  founded: "1916",
  founderStory: "Founded by Hagop Garabedian",
  primaryDomain: process.env.NEXT_PUBLIC_PRIMARY_DOMAIN || "",
  googleReviewLink: process.env.NEXT_PUBLIC_GOOGLE_REVIEW_LINK || "#",
  googleWriteReviewLink: "https://search.google.com/local/writereview?placeid=ChIJb-pZpo8G5IkR6-gkX-i8GUg",
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "About", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
  footerServices: [
    { label: "Emergency Service", href: "/contact" },
    { label: "Plumbing Repair", href: "/services" },
    { label: "Heating Systems", href: "/services" },
    { label: "Air Conditioning", href: "/services" },
  ],
  footerCompany: [
    { label: "About Us", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
} as const;
